![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [111]:
import sys
import numpy as np

## Basic Numpy Arrays

Creamos un arreglo de una dimensión con los elementos 1, 2, 3 y 4
El resultado será un objeto de tipo numpy.ndarray

In [112]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [113]:
a = np.array([1, 2, 3, 4])

In [114]:
b = np.array([0, .5, 1, 1.5, 2])

In [115]:
a[0], a[1] # Accedemos a los elementos de la lista

(1, 2)

In [116]:
a[0:] # Obtiene todos los elementos del arreglo 'a' desde el índice 0 hasta el final.

array([1, 2, 3, 4])

In [117]:
a[1:3] # Obtiene un segmento del arreglo 'a' que incluye los elementos desde el índice 1 hasta el índice 2 (exclusivo).

array([2, 3])

In [118]:
a[1:-1]  # Obtiene un segmento del arreglo 'a' que incluye los elementos desde el índice 1 hasta el penúltimo elemento.

array([2, 3])

In [119]:
a[::2]  # Obtiene un segmento del arreglo 'a' que incluye elementos con un paso de 2.

array([1, 3])

In [120]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [121]:
b[0], b[2], b[-1]  # Accede a los elementos del arreglo 'b' en las posiciones 0, 2 y la última posición.

(0.0, 1.0, 2.0)

In [122]:
b[[0, 2, -1]]  # Obtiene un nuevo arreglo con los elementos del arreglo 'b' en las posiciones 0, 2 y la última posición.

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [123]:
a

array([1, 2, 3, 4])

In [124]:
a.dtype  # Devuelve el tipo de datos de los elementos en el arreglo 'a'.

dtype('int32')

In [125]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [126]:
b.dtype  # Devuelve el tipo de datos de los elementos en el arreglo 'b'.

dtype('float64')

In [127]:
np.array([1, 2, 3, 4], dtype=np.float)  # Crea un arreglo con los elementos 1, 2, 3 y 4 con tipo de datos float.

C:\Users\victo\AppData\Local\Temp\ipykernel_14176\3277037760.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)  # Crea un arreglo con los elementos 1, 2, 3 y 4 con tipo de datos float.


array([1., 2., 3., 4.])

In [128]:
np.array([1, 2, 3, 4], dtype=np.int8)  # Crea un arreglo con los elementos 1, 2, 3 y 4 con tipo de datos int8.

array([1, 2, 3, 4], dtype=int8)

In [129]:
c = np.array(['a', 'b', 'c'])  # Crea un arreglo con los elementos 'a', 'b' y 'c'.

In [130]:
c.dtype  # Devuelve el tipo de datos de los elementos en el arreglo 'c'.

dtype('<U1')

In [131]:
d = np.array([{'a': 1}, sys])  # Crea un arreglo con un diccionario y el objeto 'sys'.

In [132]:
d.dtype  # Devuelve el tipo de datos de los elementos en el arreglo 'd'.

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [133]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])  # Crea una matriz (arreglo 2D) con los elementos 1, 2, 3 en la primera fila y 4, 5, 6 en la segunda fila.

In [134]:
A.shape  # Devuelve la forma (dimensiones) de la matriz 'A'.

(2, 3)

In [135]:
A.ndim  # Devuelve el número de dimensiones de la matriz 'A'.

2

In [136]:
A.size  # Devuelve el número total de elementos en la matriz 'A'.

6

In [137]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])  # Crea un arreglo 3D (tensor) con dos matrices 2D.

In [138]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [139]:
B.shape  # Devuelve la forma (dimensiones) del tensor 'B'.

(2, 2, 3)

In [140]:
B.ndim  # Devuelve el número de dimensiones del tensor 'B'.

3

In [141]:
B.size  # Devuelve el número total de elementos en el tensor 'B'.

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [142]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])  # Crea un arreglo 3D (tensor) con dos bloques, uno con una matriz 2D y otro con una matriz 1D.

C:\Users\victo\AppData\Local\Temp\ipykernel_14176\3392807096.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [143]:
C.dtype  # Devuelve el tipo de datos de los elementos en el tensor 'C'.

dtype('O')

In [144]:
C.shape  # Devuelve la forma (dimensiones) del tensor 'C'.

(2,)

In [145]:
C.size  # Devuelve el número total de elementos en el tensor 'C'.

2

In [146]:
type(C[0])  # Devuelve el tipo de datos del primer bloque del tensor 'C'.

list

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [147]:
# Square matrix
A = np.array([
    [1, 2, 3],  # Fila 0: Elementos 1, 2 y 3
    [4, 5, 6],  # Fila 1: Elementos 4, 5 y 6
    [7, 8, 9]   # Fila 2: Elementos 7, 8 y 9
])

In [148]:
A[1]  # Accede a la segunda fila de la matriz 'A'.

array([4, 5, 6])

In [149]:
A[1][0]  # Accede al elemento en la posición (1, 0) de la matriz 'A'.

4

In [150]:
# A[d1, d2, d3, d4]

In [151]:
A[1, 0]  # Accede al elemento en la posición (1, 0) de la matriz 'A'.

4

In [152]:
A[0:2]  # Obtiene un segmento de la matriz 'A' que incluye las filas desde la 0 hasta la 1 (exclusivo).

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
A[:, :2]  # Obtiene un segmento de la matriz 'A' que incluye todas las filas y las dos primeras columnas.

array([[1, 2],
       [4, 5],
       [7, 8]])

In [154]:
A[:2, :2]  # Obtiene un subconjunto de la matriz 'A' que incluye las dos primeras filas y las dos primeras columnas.

array([[1, 2],
       [4, 5]])

In [155]:
A[:2, 2:]  # Obtiene un subconjunto de la matriz 'A' que incluye las dos primeras filas y las columnas a partir de la tercera.

array([[3],
       [6]])

In [156]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [157]:
A[1] = np.array([10, 10, 10])  # Asigna una nueva fila a la fila índice 1 de la matriz 'A'.

In [158]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [159]:
A[2] = 99  # Asigna el valor 99 a la fila índice 2 de la matriz 'A'.

In [160]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [161]:
a = np.array([1, 2, 3, 4])  # Crea un arreglo 'a' con los elementos 1, 2, 3 y 4.

In [162]:
a.sum()  # Obtiene la suma de todos los elementos del arreglo 'a'.

10

In [163]:
a.mean()  # Obtiene el valor promedio de los elementos en el arreglo 'a'.

2.5

In [164]:
a.std()  # Obtiene la desviación estándar de los elementos en el arreglo 'a'.

1.118033988749895

In [165]:
a.var()  # Obtiene la varianza de los elementos en el arreglo 'a'.

1.25

In [166]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])  # Crea una matriz 'A' de 3x3 con los elementos del 1 al 9.

In [167]:
A.sum()  # Obtiene la suma de todos los elementos en la matriz 'A'.

45

In [168]:
A.mean()  # Obtiene el valor promedio de todos los elementos en la matriz 'A'.

5.0

In [169]:
A.std()  # Obtiene la desviación estándar de los elementos en la matriz 'A'.

2.581988897471611

In [170]:
A.sum(axis=0)  # Obtiene la suma de los elementos en cada columna de la matriz 'A'.

array([12, 15, 18])

In [171]:
A.sum(axis=1)  # Obtiene la suma de los elementos en cada fila de la matriz 'A'.

array([ 6, 15, 24])

In [172]:
A.mean(axis=0)  # Obtiene el valor promedio de los elementos en cada columna de la matriz 'A'.

array([4., 5., 6.])

In [173]:
A.mean(axis=1)  # Obtiene el valor promedio de los elementos en cada fila de la matriz 'A'.

array([2., 5., 8.])

In [174]:
A.std(axis=0)  # Obtiene la desviación estándar de los elementos en cada columna de la matriz 'A'.

array([2.44948974, 2.44948974, 2.44948974])

In [175]:
A.std(axis=1)  # Obtiene la desviación estándar de los elementos en cada fila de la matriz 'A'.

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [176]:
a = np.arange(4)  # Crea un arreglo 'a' con valores desde 0 hasta 3 (exclusivo).

In [177]:
a

array([0, 1, 2, 3])

In [178]:
a + 10  # Suma 10 a cada elemento del arreglo 'a'.

array([10, 11, 12, 13])

In [179]:
a * 10  # Multiplica cada elemento del arreglo 'a' por 10.

array([ 0, 10, 20, 30])

In [180]:
a

array([0, 1, 2, 3])

In [181]:
a += 100  # Incrementa en 100 cada elemento del arreglo 'a'.

In [182]:
a

array([100, 101, 102, 103])

In [183]:
l = [0, 1, 2, 3]  # Crea una lista 'l' con los elementos 0, 1, 2 y 3.

In [184]:
[i * 10 for i in l]  # Crea una nueva lista multiplicando cada elemento de 'l' por 10.

[0, 10, 20, 30]

In [185]:
a = np.arange(4)  # Crea un arreglo 'a' con valores desde 0 hasta 3 (exclusivo).

In [186]:
a

array([0, 1, 2, 3])

In [187]:
b = np.array([10, 10, 10, 10])  # Crea un arreglo 'b' con cuatro elementos, todos iguales a 10.

In [188]:
b

array([10, 10, 10, 10])

In [189]:
a + b  # Realiza la suma elemento a elemento de los arreglos 'a' y 'b'.

array([10, 11, 12, 13])

In [190]:
a * b  # Realiza la multiplicación elemento a elemento de los arreglos 'a' y 'b'.

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [191]:
a = np.arange(4)  # Crea un arreglo 'a' con valores desde 0 hasta 3 (exclusivo).

In [192]:
a

array([0, 1, 2, 3])

In [193]:
a[0], a[-1]  # Accede al primer elemento (a[0]) y al último elemento (a[-1]) de la lista 'a'.

(0, 3)

In [194]:
a[[0, -1]]  # Obtiene una nueva lista que contiene el primer elemento (a[0]) y el último elemento (a[-1]) de la lista 'a'.

array([0, 3])

In [195]:
a[[True, False, False, True]]  # Obtiene una nueva lista que contiene los elementos de 'a' cuyos índices son True en la lista de índices booleanos [True, False, False, True].

array([0, 3])

In [196]:
a

array([0, 1, 2, 3])

In [197]:
a >= 2  # Devuelve una lista de valores booleanos indicando si cada elemento en 'a' es mayor o igual que 2.

array([False, False,  True,  True])

In [198]:
a[a >= 2]  # Devuelve una nueva lista que contiene solo los elementos de 'a' que cumplen la condición de ser mayores o iguales a 2.

array([2, 3])

In [199]:
a.mean()  # Calcula el valor promedio (media) de todos los elementos en la lista 'a'.

1.5

In [200]:
a[a > a.mean()]  # Devuelve una nueva lista que contiene solo los elementos de 'a' que son mayores que el valor promedio (media) de todos los elementos en la lista 'a'.

array([2, 3])

In [201]:
a[~(a > a.mean())]  # Devuelve una nueva lista que contiene solo los elementos de 'a' que NO son mayores que el valor promedio (media) de todos los elementos en la lista 'a'.

array([0, 1])

In [202]:
a[(a == 0) | (a == 1)]  # Devuelve una nueva lista que contiene solo los elementos de 'a' que son iguales a 0 o 1, utilizando operadores lógicos OR (|).

array([0, 1])

In [203]:
a[(a <= 2) & (a % 2 == 0)]  # Devuelve una nueva lista que contiene solo los elementos de 'a' que son menores o iguales a 2 y además son números pares (divisibles por 2). Utiliza operadores lógicos AND (&) para combinar las condiciones.

array([0, 2])

In [204]:
A = np.random.randint(100, size=(3, 3)) # Crear una matriz 3x3 con valores enteros aleatorios entre 0 y 99.

In [205]:
A

array([[10,  4, 46],
       [ 5, 90, 55],
       [39, 16, 68]])

In [206]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]  # Selecciona los elementos de la matriz 'A' donde los valores del array booleano son True.

array([10, 46, 90, 39, 68])

In [207]:
A > 30  # Devuelve una matriz booleana del mismo tamaño que 'A' indicando qué elementos son mayores que 30.

array([[False, False,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [208]:
A[A > 30]  # Devuelve un nuevo array que contiene solo los elementos de 'A' que son mayores que 30.

array([46, 90, 55, 39, 68])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [209]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])  # Crear una matriz 3x3 llamada 'A' con los valores proporcionados.

In [210]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
]) # Creamos una matriz 3x2 llamada "B" con los valores proporcionados

In [211]:
A.dot(B) # Calcula el producto punto entre las matrices A y B.

array([[20, 14],
       [56, 41],
       [92, 68]])

In [212]:
A @ B # Esta línea de código también calcula el producto punto entre las matrices A y B. En Python, el operador `@` se utiliza para realizar la multiplicación de matrices, lo que resulta en una nueva matriz con el resultado del producto punto.

array([[20, 14],
       [56, 41],
       [92, 68]])

In [213]:
B.T # Devuelve la matriz transpuesta de B intercambiando filas por columnas.

array([[6, 4, 2],
       [5, 3, 1]])

In [214]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [215]:
B.T @ A # Realiza la multiplicación entre la matriz transpuesta de B y la matriz A, lo que resulta en una nueva matriz producto.

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [216]:
sys.getsizeof(1) # An integer in Python is > 24bytes

28

In [217]:
sys.getsizeof(10**100) # Longs are even larger

72

In [218]:
np.dtype(int).itemsize # Numpy size is much smaller

4

In [219]:
np.dtype(np.int8).itemsize # Numpy size is much smaller

1

In [220]:
np.dtype(float).itemsize # Devuelve el tamaño en bytes de un elemento del tipo de dato 'float' utilizando la biblioteca NumPy (np).

8

### Lists are even larger

In [221]:
sys.getsizeof([1]) # A one-element list

64

In [222]:
np.array([1]).nbytes # An array of one element in numpy

4

### And performance is also important

In [223]:
l = list(range(100000)) # Crea una lista 'l' que contiene números enteros desde 0 hasta 99999 (un total de 100000 elementos).

In [224]:
a = np.arange(100000)  # Crea un arreglo 'a' con números enteros desde 0 hasta 99999.

In [225]:
%time np.sum(a ** 2)  # Mide el tiempo de ejecución para calcular la suma de los cuadrados de los elementos del arreglo 'a' utilizando NumPy.

CPU times: total: 0 ns
Wall time: 1 ms


216474736

In [226]:
%time sum([x ** 2 for x in l]) # Mide el tiempo de ejecución para calcular la suma de los cuadrados de cada elemento de la lista 'l' utilizando una comprensión de lista.

CPU times: total: 15.6 ms
Wall time: 28.5 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random`
La librería NumPy tiene un módulo llamado random que se utiliza para generar números aleatorios

In [227]:
np.random.random(size=2) # Genera un arreglo con 2 números aleatorios en el rango [0.0, 1.0) utilizando la función random de NumPy.

array([0.72564141, 0.26490269])

In [228]:
np.random.normal(size=2)  # Genera un arreglo con 2 números aleatorios distribuidos normalmente (media 0, desviación estándar 1).

array([ 0.84565965, -0.64284569])

In [229]:
np.random.rand(2, 4)  # Genera una matriz de tamaño 2x4 con valores aleatorios en el rango [0.0, 1.0).

array([[0.468339  , 0.9660362 , 0.46160836, 0.78845819],
       [0.19415277, 0.92516287, 0.67081644, 0.26538028]])

---
### `arange`
La función arange() de NumPy se utiliza para crear una matriz de valores espaciados uniformemente dentro de un intervalo

In [230]:
np.arange(10)  # Crea un arreglo que contiene valores desde 0 hasta 9 utilizando la función arange de NumPy.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
np.arange(5, 10)  # Crea un arreglo que contiene valores desde 5 hasta 9 utilizando np.arange.

array([5, 6, 7, 8, 9])

In [232]:
np.arange(0, 1, 0.1)  # Crea un arreglo con valores desde 0.0 hasta 0.9, con incrementos de 0.1 utilizando np.arange.

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`
La función reshape() de NumPy se utiliza para cambiar la forma de una matriz sin cambiar sus datos

In [233]:
np.arange(10).reshape(2, 5)  # Crea una matriz 2x5 con valores desde 0 hasta 9 utilizando np.arange.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [234]:
np.arange(10).reshape(5, 2)  # Crea una matriz 5x2 con valores desde 0 hasta 9 utilizando np.arange.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`
La función linspace() de NumPy se utiliza para crear una matriz de valores espaciados uniformemente dentro de un intervalo.

In [235]:
np.linspace(0, 1, 5) # Crea un arreglo con 5 valores equidistantes entre 0 y 1 (incluyendo 0 y 1).

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [236]:
np.linspace(0, 1, 20) # Crea un arreglo con 20 valores equidistantes entre 0 y 1 (incluyendo 0 y 1).

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [237]:
np.linspace(0, 1, 20, False) # Crea un arreglo con 20 valores equidistantes entre 0 y 1 (excluyendo 1).

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`
Las funciones zeros(), ones() y empty() de NumPy se utilizan para crear matrices de ceros, unos y valores no inicializados, respectivamente

In [238]:
np.zeros(5) # Crea un array de ceros de longitud 5 utilizando NumPy.

array([0., 0., 0., 0., 0.])

In [239]:
np.zeros((3, 3)) # Crea una matriz de ceros de tamaño 3x3 utilizando NumPy.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [251]:
np.zeros((3, 3), dtype=int) # Crea una matriz de ceros de tamaño 3x3 con tipo de dato entero utilizando NumPy.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [241]:
np.ones(5) # Crea un array de unos de longitud 5 utilizando NumPy.

array([1., 1., 1., 1., 1.])

In [242]:
np.ones((3, 3)) # Crea una matriz de unos de tamaño 3x3 utilizando NumPy.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [243]:
np.empty(5) # Crea un array vacío de longitud 5 utilizando NumPy. Es importante tener en cuenta que los valores en este array no están inicializados y pueden contener cualquier valor residual de la memoria.

array([1., 1., 1., 1., 1.])

In [244]:
np.empty((2, 2)) # Crea una matriz vacía de tamaño 2x2 utilizando NumPy. Al igual que en el caso anterior, los valores en esta matriz no están inicializados y pueden contener cualquier valor residual de la memoria.

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`
Las funciones identity() y eye() de NumPy se utilizan para crear matrices de identidad

In [245]:
np.identity(3) # Crea una matriz identidad de tamaño 3x3 utilizando NumPy. Una matriz identidad es una matriz cuadrada con unos en la diagonal principal y ceros en todas las demás posiciones.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [246]:
np.eye(3, 3) # Crea una matriz de tamaño 3x3 con unos en la diagonal principal y ceros en todas las demás posiciones utilizando NumPy. Es esencialmente igual a una matriz identidad de tamaño 3x3.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [247]:
np.eye(8, 4) # Crea una matriz de tamaño 8x4 con unos en la diagonal principal y ceros en todas las demás posiciones utilizando NumPy. Esta matriz es una matriz con forma rectangular y se conoce como una matriz con una "banda diagonal".

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [248]:
np.eye(8, 4, k=1) # Crea una matriz de tamaño 8x4 con unos en la primera diagonal superior (k=1) y ceros en todas las demás posiciones utilizando NumPy. Esta matriz tendrá unos en la posición (i, i+1) y ceros en todas las demás posiciones.

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [249]:
np.eye(8, 4, k=-3) # Este código crea una matriz de 8x4 con 1’s en la diagonal que comienza en la tercera fila y termina en la última fila

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [250]:
"Hello World"[6] # Este código devuelve el carácter en la posición 6 de la cadena “Hello World”, que es “W”

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)